name: Feature Request
description: Suggest an idea or improvement
labels: ["type:enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the idea!

        If you meant to report a bug, please use the Bug Report template:
        https://github.com/raven-dev-ops/EA_Sports_FC_26_Discord_Bot/issues/new?template=bug_report.yml

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What do you want to add or change?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Bullet list of done conditions.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Links to related issues, commands, or channels.
    validations:
      required: false
