DISCORD_TOKEN_ENV = "DISCORD_TOKEN"
DISCORD_APPLICATION_ID_ENV = "DISCORD_APPLICATION_ID"
DISCORD_CLIENT_ID_ENV = "DISCORD_CLIENT_ID"
DISCORD_PUBLIC_KEY_ENV = "DISCORD_PUBLIC_KEY"
DISCORD_INTERACTIONS_ENDPOINT_URL_ENV = "DISCORD_INTERACTIONS_ENDPOINT_URL"

ROLE_BROSKIE_ID_ENV = "ROLE_BROSKIE_ID"
ROLE_SUPER_LEAGUE_COACH_ID_ENV = "ROLE_SUPER_LEAGUE_COACH_ID"
ROLE_COACH_PREMIUM_ID_ENV = "ROLE_COACH_PREMIUM_ID"
ROLE_COACH_PREMIUM_PLUS_ID_ENV = "ROLE_COACH_PREMIUM_PLUS_ID"

CHANNEL_ROSTER_PORTAL_ID_ENV = "CHANNEL_ROSTER_PORTAL_ID"
CHANNEL_STAFF_SUBMISSIONS_ID_ENV = "CHANNEL_STAFF_SUBMISSIONS_ID"

STAFF_ROLE_IDS_ENV = "STAFF_ROLE_IDS"

MONGODB_URI_ENV = "MONGODB_URI"
MONGODB_DB_NAME_ENV = "MONGODB_DB_NAME"
MONGODB_COLLECTION_ENV = "MONGODB_COLLECTION"
