DISCORD_TOKEN_ENV = "DISCORD_TOKEN"
DISCORD_APPLICATION_ID_ENV = "DISCORD_APPLICATION_ID"
DISCORD_CLIENT_ID_ENV = "DISCORD_CLIENT_ID"
DISCORD_PUBLIC_KEY_ENV = "DISCORD_PUBLIC_KEY"
DISCORD_INTERACTIONS_ENDPOINT_URL_ENV = "DISCORD_INTERACTIONS_ENDPOINT_URL"
TEST_MODE_ENV = "TEST_MODE"

ROLE_BROSKIE_ID_ENV = "ROLE_BROSKIE_ID"
ROLE_TEAM_COACH_ID_ENV = "ROLE_TEAM_COACH_ID"
ROLE_CLUB_MANAGER_ID_ENV = "ROLE_CLUB_MANAGER_ID"
ROLE_LEAGUE_STAFF_ID_ENV = "ROLE_LEAGUE_STAFF_ID"
ROLE_LEAGUE_OWNER_ID_ENV = "ROLE_LEAGUE_OWNER_ID"
ROLE_FREE_AGENT_ID_ENV = "ROLE_FREE_AGENT_ID"
ROLE_PRO_PLAYER_ID_ENV = "ROLE_PRO_PLAYER_ID"
ROLE_RETIRED_ID_ENV = "ROLE_RETIRED_ID"

# Backwards compatibility (legacy tier names)
ROLE_COACH_ID_ENV = "ROLE_COACH_ID"
ROLE_COACH_PREMIUM_ID_ENV = "ROLE_COACH_PREMIUM_ID"
ROLE_COACH_PREMIUM_PLUS_ID_ENV = "ROLE_COACH_PREMIUM_PLUS_ID"
ROLE_SUPER_LEAGUE_COACH_ID_ENV = "ROLE_SUPER_LEAGUE_COACH_ID"

CHANNEL_COACH_PORTAL_ID_ENV = "CHANNEL_COACH_PORTAL_ID"
CHANNEL_STAFF_PORTAL_ID_ENV = "CHANNEL_STAFF_PORTAL_ID"
CHANNEL_RECRUIT_PORTAL_ID_ENV = "CHANNEL_RECRUIT_PORTAL_ID"
CHANNEL_CLUB_PORTAL_ID_ENV = "CHANNEL_CLUB_PORTAL_ID"
CHANNEL_MANAGER_PORTAL_ID_ENV = "CHANNEL_MANAGER_PORTAL_ID"

CHANNEL_STAFF_MONITOR_ID_ENV = "CHANNEL_STAFF_MONITOR_ID"
CHANNEL_RECRUIT_LISTING_ID_ENV = "CHANNEL_RECRUIT_LISTING_ID"
CHANNEL_CLUB_LISTING_ID_ENV = "CHANNEL_CLUB_LISTING_ID"
CHANNEL_PREMIUM_COACHES_ID_ENV = "CHANNEL_PREMIUM_COACHES_ID"

# Backwards compatibility (mapped to club listings)
CHANNEL_ROSTER_LISTING_ID_ENV = "CHANNEL_ROSTER_LISTING_ID"
CHANNEL_ROSTER_PORTAL_ID_ENV = "CHANNEL_ROSTER_PORTAL_ID"

STAFF_ROLE_IDS_ENV = "STAFF_ROLE_IDS"

MONGODB_URI_ENV = "MONGODB_URI"
MONGODB_DB_NAME_ENV = "MONGODB_DB_NAME"
MONGODB_COLLECTION_ENV = "MONGODB_COLLECTION"
MONGODB_PER_GUILD_DB_ENV = "MONGODB_PER_GUILD_DB"
MONGODB_GUILD_DB_PREFIX_ENV = "MONGODB_GUILD_DB_PREFIX"

BANLIST_SHEET_ID_ENV = "BANLIST_SHEET_ID"
BANLIST_RANGE_ENV = "BANLIST_RANGE"
BANLIST_CACHE_TTL_SECONDS_ENV = "BANLIST_CACHE_TTL_SECONDS"
GOOGLE_SHEETS_CREDENTIALS_JSON_ENV = "GOOGLE_SHEETS_CREDENTIALS_JSON"

USE_SHARDING_ENV = "USE_SHARDING"
SHARD_COUNT_ENV = "SHARD_COUNT"
FEATURE_FLAGS_ENV = "FEATURE_FLAGS"

# FC25 stats integration (optional; gated by FEATURE_FLAGS)
FC25_STATS_CACHE_TTL_SECONDS_ENV = "FC25_STATS_CACHE_TTL_SECONDS"
FC25_STATS_HTTP_TIMEOUT_SECONDS_ENV = "FC25_STATS_HTTP_TIMEOUT_SECONDS"
FC25_STATS_MAX_CONCURRENCY_ENV = "FC25_STATS_MAX_CONCURRENCY"
FC25_STATS_RATE_LIMIT_PER_GUILD_ENV = "FC25_STATS_RATE_LIMIT_PER_GUILD"
FC25_DEFAULT_PLATFORM_ENV = "FC25_DEFAULT_PLATFORM"
